# Generated by Django 3.1.3 on 2021-04-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gharapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
