# Generated by Django 3.1.3 on 2021-04-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/image/bedroom.jpg', upload_to='static/uploads'),
        ),
    ]
